libnodectld: symbolize names read from config
The names in the config must no longer be prefixed with colons in order
to be turned into symbol. All names are symbolized automatically.

(cherry picked from commit d842cc439c118dc8d800e76903011d9d319e7a7a)