libnodectld: workaround nil mysql result
This should fix the following crash:

undefined method `each' for nil (NoMethodError)
    from lib/nodectld/db.rb:216:in `each'
        @result.each(&)
              ^^^^^
    from lib/nodectld/db.rb:204:in `block in each'
    from lib/nodectld/db.rb:203:in `each'
    from lib/nodectld/db.rb:203:in `each'
    from lib/nodectld/daemon.rb:269:in `do_commands'
    from lib/nodectld/daemon.rb:150:in `work'
    from lib/nodectld/daemon.rb:109:in `block in start'
    from <internal:kernel>:187:in `loop'
    from lib/nodectld/daemon.rb:105:in `start'
    from lib/nodectld/cli.rb:174:in `run_daemon'
    from lib/nodectld/cli.rb:100:in `block (2 levels) in run_wrapper'
    from lib/nodectld/cli.rb:95:in `fork'
    from lib/nodectld/cli.rb:95:in `block in run_wrapper'
    from <internal:kernel>:187:in `loop'
    from lib/nodectld/cli.rb:92:in `run_wrapper'
    from lib/nodectld/cli.rb:77:in `run'
    from lib/nodectld/cli.rb:12:in `run'
    from bin/nodectld:4:in `<top (required)>'
    from bin/nodectld:35:in `load'
    from bin/nodectld:35:in `<main>'